# Generated by Django 4.2.7 on 2024-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_contactus_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='Path')),
                ('request_method', models.CharField(max_length=64, verbose_name='Request method')),
                ('time', models.DecimalField(decimal_places=10, max_digits=14, verbose_name='Time')),
            ],
        ),
    ]
